build:
	g++ src/solver/solver.cpp src/solver/monte.cpp src/solver/func.cpp -o bin/solver
	g++ src/sender.cpp -o bin/sender


solver:
	g++ src/solver/solver.cpp src/solver/monte.cpp src/solver/func.cpp -o bin/solver


sender:
	g++ src/sender.cpp -o bin/sender

run_solver:
	./bin/solver

run_sender:
	./bin/sender